name = "EvidentialFlux"
uuid = "c214720e-3c4f-4d89-8b85-b9ea3aac2a05"
authors = ["Michael Green <micke.green@gmail.com> and contributors"]
version = "1.3.1"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Flux = "0.13"
julia = "1.7"
NNlib = "0.8"
SpecialFunctions = "2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
